"""empty message

Revision ID: d5efd14656be
Revises: 
Create Date: 2023-07-11 17:13:26.015550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5efd14656be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_tool_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True, comment='1: HW_Monitor 2: tobe add'),
    sa.Column('params', sa.JSON(), nullable=True, comment='工具参数'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_tool_records')
    # ### end Alembic commands ###
