"""empty message

Revision ID: ed24b0b67215
Revises: 
Create Date: 2023-10-23 19:09:23.062282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed24b0b67215'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_task_id'), 'reports', ['task_id'], unique=False)
    op.create_table('run_tool_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True, comment='1: HW_Monitor 2: tobe add'),
    sa.Column('params', sa.JSON(), nullable=True, comment='工具参数'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=80), nullable=False),
    sa.Column('env', sa.JSON(), nullable=True, comment='env参数变量'),
    sa.Column('mark', sa.String(length=80), nullable=True),
    sa.Column('vol', sa.JSON(), nullable=True, comment='挂载参数'),
    sa.Column('pipeline_id', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True, comment='1: running 2: finished'),
    sa.Column('result', sa.JSON(), nullable=True, comment='测试结果'),
    sa.Column('report', sa.String(length=512), nullable=True),
    sa.Column('command', sa.String(length=256), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='1: Admin, 2: Project Admin, 3: Common User'),
    sa.Column('menu_ids', sa.JSON(), nullable=True, comment='页面访问权限'),
    sa.Column('accces_apis', sa.JSON(), nullable=True, comment='接口访问权限'),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('run_tool_records')
    op.drop_index(op.f('ix_reports_task_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('projects')
    # ### end Alembic commands ###
